
drop table if exists BANKACCOUNT;
drop table if exists TRANSACTION;
CREATE TABLE BANKACCOUNT(
ACCOUNTID VARCHAR(16) PRIMARY KEY,
 AMOUNT varchar(20),
 FIRSTNAME VARCHAR(50),
  LASTNAME VARCHAR(50),
   DATEOFBIRTH VARCHAR(15),
   ACCOUNTCREATIONDATE DATE,
   ACCOUNTTYPE VARCHAR(20) );

   CREATE TABLE TRANSACTION(
   TRANSACTIONID VARCHAR(20) PRIMARY KEY,
   ACCOUNTID VARCHAR(20),
   TRANSACTIONTYPE VARCHAR(20),
   DEPOSITAMOUNT VARCHAR(20),
   WITHDRAWLAMOUNT VARCHAR(20)
   );



